stages:
  - build
  - test
  - quality

variables:
  MAVEN_CLI_OPTS: "-s ./.m2/settings.xml --batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

before_script:
  - apt-get update -qq && apt-get install -qq -y curl unzip
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install maven

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

checkstyle:
  stage: quality
  script:
    - mvn $MAVEN_CLI_OPTS checkstyle:check
  artifacts:
    paths:
      - target/checkstyle-result.xml

pmd:
  stage: quality
  script:
    - mvn $MAVEN_CLI_OPTS pmd:pmd
  artifacts:
    paths:
      - target/pmd.xml

spotbugs:
  stage: quality
  script:
    - mvn $MAVEN_CLI_OPTS spotbugs:check
  artifacts:
    paths:
      - target/spotbugsXml.xml

jacoco:
  stage: quality
  script:
    - mvn $MAVEN_CLI_OPTS jacoco:report
  artifacts:
    paths:
      - target/site/jacoco
